### ISSUE TITLE
Adjust reference to 41 and Kite in the help text

### ISSUE THREAD

**Issue by wolftune** [wilckerson/microtonal-tuner#7]
After "For example, some music has been written in 24edo (quartertones), 19edo and 31edo." Add this sentence at the end of paragraph:

> The Kite Guitar uses 41edo.

And link the "Kite Guitar" text.

And then remove the bullet that mentioned 41/4 and kite later.

Note that it's a little weird that 22 and not 24 is in the defaults, but only 24 is mentioned in the help.

**Comment by wilckerson** [comment]
Thanks for the feedback. 

These items are now fixed on v1.3.0

I have also implemented the link to open the Tuner direct on 41edo for use on Kite Guitar's website.
https://microtonal-tuner.herokuapp.com/tuning/41edo
